/**
 * TubeBuddy Notification API
 * TubeBuddy tweet notifications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaron@tubebuddy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TubeBuddyNotificationApi);
  }
}(this, function(expect, TubeBuddyNotificationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TubeBuddyNotificationApi.Tweets();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Tweets', function() {
    it('should create an instance of Tweets', function() {
      // uncomment below and update the code to test Tweets
      //var instane = new TubeBuddyNotificationApi.Tweets();
      //expect(instance).to.be.a(TubeBuddyNotificationApi.Tweets);
    });

    it('should have the property id (base name: "Id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new TubeBuddyNotificationApi.Tweets();
      //expect(instance).to.be();
    });

    it('should have the property handle (base name: "Handle")', function() {
      // uncomment below and update the code to test the property handle
      //var instane = new TubeBuddyNotificationApi.Tweets();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new TubeBuddyNotificationApi.Tweets();
      //expect(instance).to.be();
    });

    it('should have the property thumbnailUrl (base name: "ThumbnailUrl")', function() {
      // uncomment below and update the code to test the property thumbnailUrl
      //var instane = new TubeBuddyNotificationApi.Tweets();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "Date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new TubeBuddyNotificationApi.Tweets();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "Text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new TubeBuddyNotificationApi.Tweets();
      //expect(instance).to.be();
    });

  });

}));
