/**
 * TubeBuddy Notification API
 * TubeBuddy tweet notifications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaron@tubebuddy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Tweets model module.
* @module model/Tweets
* @version 1.0.0
*/
export default class Tweets {
    /**
    * Constructs a new <code>Tweets</code>.
    * @alias module:model/Tweets
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Tweets</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Tweets} obj Optional instance to populate.
    * @return {module:model/Tweets} The populated <code>Tweets</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tweets();

            
            
            

            if (data.hasOwnProperty('Id')) {
                obj['Id'] = ApiClient.convertToType(data['Id'], 'String');
            }
            if (data.hasOwnProperty('Handle')) {
                obj['Handle'] = ApiClient.convertToType(data['Handle'], 'String');
            }
            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('ThumbnailUrl')) {
                obj['ThumbnailUrl'] = ApiClient.convertToType(data['ThumbnailUrl'], 'String');
            }
            if (data.hasOwnProperty('Date')) {
                obj['Date'] = ApiClient.convertToType(data['Date'], 'String');
            }
            if (data.hasOwnProperty('Text')) {
                obj['Text'] = ApiClient.convertToType(data['Text'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} Id
    */
    Id = undefined;
    /**
    * @member {String} Handle
    */
    Handle = undefined;
    /**
    * @member {String} Name
    */
    Name = undefined;
    /**
    * @member {String} ThumbnailUrl
    */
    ThumbnailUrl = undefined;
    /**
    * @member {String} Date
    */
    Date = undefined;
    /**
    * @member {String} Text
    */
    Text = undefined;








}


