/**
 * TubeBuddy Notification API
 * TubeBuddy tweet notifications
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaron@tubebuddy.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Tweets from './Tweets';





/**
* The Item model module.
* @module model/Item
* @version 1.0.0
*/
export default class Item {
    /**
    * Constructs a new <code>Item</code>.
    * @alias module:model/Item
    * @class
    * @param channelId {String} 
    * @param twitterAccount {String} 
    * @param tweets {module:model/Tweets} 
    */

    constructor(channelId, twitterAccount, tweets) {
        

        
        

        this['ChannelId'] = channelId;this['TwitterAccount'] = twitterAccount;this['Tweets'] = tweets;

        
    }

    /**
    * Constructs a <code>Item</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Item} obj Optional instance to populate.
    * @return {module:model/Item} The populated <code>Item</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Item();

            
            
            

            if (data.hasOwnProperty('ChannelId')) {
                obj['ChannelId'] = ApiClient.convertToType(data['ChannelId'], 'String');
            }
            if (data.hasOwnProperty('TwitterAccount')) {
                obj['TwitterAccount'] = ApiClient.convertToType(data['TwitterAccount'], 'String');
            }
            if (data.hasOwnProperty('Tweets')) {
                obj['Tweets'] = Tweets.constructFromObject(data['Tweets']);
            }
        }
        return obj;
    }

    /**
    * @member {String} ChannelId
    */
    ChannelId = undefined;
    /**
    * @member {String} TwitterAccount
    */
    TwitterAccount = undefined;
    /**
    * @member {module:model/Tweets} Tweets
    */
    Tweets = undefined;








}


